### ISSUE TITLE
power_on + power_off does not display

### ISSUE THREAD

**Issue by loopphoto** [marrobHD/tv-card#12]
<img width="518" alt="Screenshot 2020-06-19 at 13 03 13" src="https://user-images.githubusercontent.com/30428657/85126623-2491dc00-b22e-11ea-9358-2efb08f95cc9.png">

![Screenshot 2020-06-19 at 13 10 26](https://user-images.githubusercontent.com/30428657/85126697-47bc8b80-b22e-11ea-979f-54951e466794.png)

I've followed the instructions but I can not get "power_on" and "power_off" to display. "power" works, but i have different commands for on and off. Everything else works perfectly, and thank you very much for the awesome work thus far!

I've tested in Chrome on MacOS, Home Assistant Companion on iPhone and Safari, all with the same issue. I'm on HA 0.111.4 on Docker and I've used HACS to install your card.

**Comment by marrobHD** [comment]
You can add power and it should work.

**Comment by mydevbox** [comment]
Can this fix be released at 0.1.4 so that HACS will pick it up as an update?

**Comment by marrobHD** [comment]
I stopped working on this card. Sorry. Pull requests are appreciated.

**Comment by marrobHD** [comment]
Fixed in [#0.1.14](https://github.com/marrobHD/tv-card/releases/tag/0.1.4)
