### ISSUE TITLE
Separate Play and Pause buttons

### ISSUE THREAD

**Issue by artgap** [marrobHD/tv-card#14]
Play button in this card is Play|Pause button. My remote have different Play and Pause buttons, so need the ability to choose between one Play|Pause button and two separate Play and Pause buttons.

**Comment by GuyLewin** [comment]
@artgap great idea, I added it to my fork at https://github.com/GuyLewin/tv-card

**Comment by marrobHD** [comment]
This card is unmaintained. Please look into: https://github.com/usernein/tv-card
