### ISSUE TITLE
menu does nothing

### ISSUE THREAD

**Issue by MCHellspawn** [marrobHD/tv-card#15]
I added the menu button but there does not seem to be a button on the remote to represent it. is it a duplicate of home?

**Comment by patzobil** [comment]
same here, you could theoretically tweak the tv-card.js....but might be best to wait for @marrobHD to publish an update

**Comment by marrobHD** [comment]
> same here, you could theoretically tweak the tv-card.js....but might be best to wait for @marrobHD to publish an update

I would like to hand this project over to someone else. I can't find enough time to solve the problems.

**Comment by marrobHD** [comment]
Fixed wrong documentation in [0.1.14](https://github.com/marrobHD/tv-card/releases/latest)
There is no menu button.
