### ISSUE TITLE
Doesn't show up in list of cards

### ISSUE THREAD

**Issue by tripplehelix** [marrobHD/tv-card#17]
**Checklist:**

- [✔️] I updated to the latest version available
- [✔️] I cleared the cache of my browser

**Release with the issue: Latest**

**Last working release (if known): N/A**

**Browser and Operating System: Chrome v90, ChromeOS v90**

**Description of problem: The integration doesn't show up in list of cards, I've installed it via HACS. HA Version core-2021.4.1**

**Comment by TheToto** [comment]
Same bug, installed with HACS
![image](https://user-images.githubusercontent.com/12860648/118153780-8f37a180-b416-11eb-9c9e-4ac9774da838.png)

**Comment by ManTreff** [comment]
Hi, same 'bug'. 
Here the installation procedure working for me (HA OS6 / v2021-6-4)
Step1: install with HACS frontend
Step2: attach ressource by using "Editing Dashboard Menu LovelaceUI"/ "Manage resources". Tv card should be already here (linked as: /hacsfiles/tv-card/tv-card.js)
Step3: With UI, Add a card/ Manual / paste this card configuration:

type: custom:tv-card
entity: sun.sun
name: Bedroom TV
tv: true
power:
..service: switch.turn_on
..service_data:
....entity_id: switch.bedroom_tv_power

(replace point by space)

**Comment by yezzerfv** [comment]
Yup, I also have this bug, installing via HACS. Tried restarting, no luck.

**Comment by marrobHD** [comment]
I'm not able to reproduce this. 
Please update to the latest hassio/hacs release and use master version in hacs for the card. Please also check if you can reach the ressource URL with your web browser.

**Comment by sxenth** [comment]
I have the same issue with a custom card that doesn't exist error. It shows up fine on my laptop but gives this error when on my phone, tablet, or mobile app. Also noticed, it gives the same error on laptop when connecting through homeassistant:8123 but works with ip_adress:8123 tried both on mobile devices and gives error ether way.

Just in case anyone sees this, I was able to resolve the issue by unintalling and reinstalling using the master version through hacs.

**Comment by lgwapnitsky** [comment]
> I have the same issue with a custom card that doesn't exist error. It shows up fine on my laptop but gives this error when on my phone, tablet, or mobile app. Also noticed, it gives the same error on laptop when connecting through homeassistant:8123 but works with ip_adress:8123 tried both on mobile devices and gives error ether way.
> 
> Just in case anyone sees this, I was able to resolve the issue by unintalling and reinstalling using the master version through hacs.

tried this, and still no luck.

**Comment by marrobHD** [comment]
This card is unmaintained. Please look into: https://github.com/usernein/tv-card
