### ISSUE TITLE
Holding down buttons = repeat command

### ISSUE THREAD

**Issue by phrz** [marrobHD/tv-card#18]
**Is your feature request related to a problem? Please describe.**
First, thank you for this wonderful card. 
In many video playing apps on my Apple TV, the right arrow button advances the video ten seconds. It takes many rapid taps to move through a long video, because the tv-card does not allow users to hold a button in order to send repeat commands. 

**Describe the solution you'd like**
It would be very helpful if, for any button, users could set a Boolean such as `repeat`, which would cause holding the button to repeatedly call the given service. Users could additionally set a delay between repeated calls, such as `repeat_delay: 100`, and even a delay from the initial tap after which the repeated calls begin. 

**Describe alternatives you've considered**
This is particular to the Apple TV but likely generalizable to other devices. The issue on Apple TV's is that the current generation of physical remotes have a touchpad, and you can trivially drag your finger across it to move through the scrubber of even a very long video. But third party controls like Home Assistant's integration only support sending discrete button presses. The pyatv library used by HA has distinct "right" (arrow) and "skip forward" commands—however both function identically in this case, only advancing ten seconds, and it seems hold-to-repeat would be the only remedy. There is no way to skip an arbitrarily large segment of video that could obviate the need for this feature.

**Comment by marrobHD** [comment]
This card is unmaintained. Please look into: https://github.com/usernein/tv-card
