### ISSUE TITLE
Implement Haptics

### ISSUE THREAD

**Issue by alexyao2015** [marrobHD/tv-card#19]
**Is your feature request related to a problem? Please describe.**
Button presses are not easy to distinguish when on mobile.
**Describe the solution you'd like**
Implement haptics as mentioned here https://companion.home-assistant.io/docs/integrations/haptics/
**Describe alternatives you've considered**

**Additional context**

**Comment by usernein** [comment]
+1 I missed it for this card

**Comment by marrobHD** [comment]
This card is unmaintained. Please look into: https://github.com/usernein/tv-card
