### ISSUE TITLE
Optional Directional Pad

### ISSUE THREAD

**Issue by vrelk** [marrobHD/tv-card#20]
**Is your feature request related to a problem? Please describe.**
I am using this to control an IR blaster, but the devices I'm controlling don't have a D-Pad (ex: stereo & projector), so having it show up is a waste of space and extra clutter.

**Describe the solution you'd like**
I am looking for a way to enable/disable the D-Pad (up/down/left/right/enter) on the remote for devices that don't support it, or only have it show up if you set the values for it like the volume buttons work.

**Comment by danielholm** [comment]
I would appreciate that as well. Make an option to make the D-pad optional.

**Comment by Marcoske23** [comment]
+1. It is posible?

**Comment by marrobHD** [comment]
This card is unmaintained. Please look into: https://github.com/usernein/tv-card
