### ISSUE TITLE
Not working from core-2021.11.0b0

### ISSUE THREAD

**Issue by n00bcodr** [marrobHD/tv-card#23]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** core-2021.11.0b0

**Last working release (if known):** core-2021.10.8

**Browser and Operating System:** Tried on Google Chrome, Edge, Firefox on MacOS and Windows 10. Also in Home Assistant app on Android

**Description of problem:**
Icons are now showing since Homeassistant core-2021.11.0b0. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

![image](https://user-images.githubusercontent.com/49611451/139817314-47e77840-ec8b-4302-a6df-ea9749458d05.png)
![image](https://user-images.githubusercontent.com/49611451/139817355-ed1037d6-afe1-4cc0-89ac-4735c42c6bea.png)

**Comment by ColinRobbins** [comment]
I have the same issue with the release: `2021.11.0`.

I cannot see anything in either the homeassistant or browser logs.

**Comment by yurbd** [comment]
mine is working, but the icons dont show

**Comment by kinorai** [comment]
Yes, I have the same problem with : Version supervisor-2021.10.8 / Version core-2021.11.0
![image](https://user-images.githubusercontent.com/32527089/140397089-5c59c612-dcd8-4fb7-8a87-54429784c67a.png)

**Comment by josrafafonlo** [comment]
I do also have this problem. It still sends the command if you touch the area where a button should be, it even shows feedback as if you truly touched it, but no icons are shown.

**Comment by ajurna** [comment]
this is still an issue in 2021.11.1

**Comment by TheZeroBeast** [comment]
I agree, still an issue with 2021.11.1

I noticed this PR #22 that might be the key although even when I force the files to have these changes the card doesn't load icons.

**Comment by blavak68** [comment]
the same problem 2021.11.1

edit:  PR [#22](https://github.com/marrobHD/tv-card/pull/22)  is the solution

**Comment by lucidnx** [comment]
same here :( please update it according to original roku remote (it is fixed already)
https://github.com/iantrich/roku-card/commit/e6d229e02472572017e7a3c1fb8734b2f47b7df3

**Comment by r0667002** [comment]
Same issue here, seems like mini media player had the same issue but is fixed now. I just rolled back the update by using `ha core update --version 2021.10.6` for now. Just open the Terminal & SSH add-on and paste the command, clear cache and it should be back.

Just saw the [PR](https://github.com/ZephireNZ/tv-card/tree/fix/2021.11) though, haven't tested but seems to work for others.

**Comment by KairuByte** [comment]
You mean PR #22, you linked the fork.

That said, it seems to correct the issue... Is this project now unmaintained?

**Comment by broyuken** [comment]
Yes I saw another commend from the fall of 2020 where they said they are no longer working on this card, so it's pretty dead. Might want to see if theres an alternative out there somewhere that someone is maintaining. Unless someone wants to pick it up and fork it.

**Comment by JRFabbi** [comment]
I've exactely same bug on "mini climate card", they already solve it on latest version.
I'm going to try to figure out what they did to fix it to see if it's possible to change something here and make it work again.

**Comment by Avatar1976** [comment]
Ah thanks guys, new to this card and couldn't figure out why it wasn't working. Good discussion!

**Comment by SgtTacooo** [comment]
@JRFabbi any luck in forking and updating code?

**Comment by JRFabbi** [comment]
> @JRFabbi any luck in forking and updating code?

Yes, someone already update this on the latest pull request

https://github.com/marrobHD/tv-card/pull/22

**Comment by blavak68** [comment]
not working in mobile app (homeassitant)

**Comment by JRFabbi** [comment]
> not working in mobile app (homeassitant)

If it is working on your computer then you have to clear you app cache.

**Comment by blavak68** [comment]
thx 

> > not working in mobile app (homeassitant)
> 
> If it is working on your computer then you have to clear you app cache.

thx it didn't occur to me -)))  everything works

**Comment by marrobHD** [comment]
I've merged the PR. Please clear the cache of the HA companion app and on the ha webui press F5 to clear cache.
