### ISSUE TITLE
Adding "select" results in mapping error 

### ISSUE THREAD

**Issue by vikdb** [marrobHD/tv-card#27]
If i try to add "select" to the remote, i get the following error:

Configuration errors detected:

duplicated mapping key (70:1)

 67 |     device: LG tv
 68 |     command: MUTE
 69 |     entity_id: remote.broadlink ...
 70 | select:
 71 |   service: script.lg_change_input
 72 

Here's my config:

**_type: custom:tv-card
entity: sun.sun
tv: true
power:
  service: remote.send_command
  service_data:
    device: LG tv
    command: POWER
    entity_id: remote.broadlink_rm4_pro_remote
down:
  service: remote.send_command
  service_data:
    device: LG tv
    command: ARROW DOWN
    entity_id: remote.broadlink_rm4_pro_remote
up:
  service: remote.send_command
  service_data:
    device: LG tv
    command: ARROW UP
    entity_id: remote.broadlink_rm4_pro_remote
left:
  service: remote.send_command
  service_data:
    device: LG tv
    command: ARROW LEFT
    entity_id: remote.broadlink_rm4_pro_remote
right:
  service: remote.send_command
  service_data:
    device: LG tv
    command: ARROW RIGHT
    entity_id: remote.broadlink_rm4_pro_remote
select:
  service: remote.send_command
  service_data:
    device: LG tv
    command: OK
    entity_id: remote.broadlink_rm4_pro_remote
back:
  service: remote.send_command
  service_data:
    device: LG tv
    command: BACK
    entity_id: remote.broadlink_rm4_pro_remote
source:
  service: remote.send_command
  service_data:
    device: LG tv
    command: INPUT
    entity_id: remote.broadlink_rm4_pro_remote
volume_up:
  service: remote.send_command
  service_data:
    device: LG tv
    command: VOLUME UP
    entity_id: remote.broadlink_rm4_pro_remote
volume_down:
  service: remote.send_command
  service_data:
    device: LG tv
    command: VOLUME DOWN
    entity_id: remote.broadlink_rm4_pro_remote
volume_mute:
  service: remote.send_command
  service_data:
    device: LG tv
    command: MUTE
    entity_id: remote.broadlink_rm4_pro_remote
select:
  service: script.lg_change_input_**

I dont get this if i make it for example the "info" button.

**Comment by marrobHD** [comment]
The message says, that there is more than one mapping key called 'select'. Look at the penultimate line. Just remove the 'select:' there.
