### ISSUE TITLE
Changing icons

### ISSUE THREAD

**Issue by garagara93** [marrobHD/tv-card#3]
Can we change the icons?

**Comment by marrobHD** [comment]
Yes you have to edit tv-card.js.
Go to https://materialdesignicons.com/ click on a icon that you like, copy the above text and replace it with the text after mdi:

Example: icon="mdi:volume-minus" > icon="mdi:minus"

Can I close this now?

**Comment by maddeuce** [comment]
Hi I tried to change the icon but the new icon is not updating.  I try reloading the resource, clean my browser/app caches nothing work as it still show the original icon.

**Comment by marrobHD** [comment]
> Hi I tried to change the icon but the new icon is not updating.  I try reloading the resource, clean my browser/app caches nothing work as it still show the original icon.

Did you edit the icon in the .js file?
Could you please show your edits?

**Comment by maddeuce** [comment]
Yes i edit the in tv-card.js
https://ghostbin.co/paste/u8sq6

**Comment by marrobHD** [comment]
Removing the entry in lovelace resources, renaming the .js file, readding lovelace resources and finally reloaded the page did the trick for me.

**Comment by maddeuce** [comment]
perfect its working much thank.  I using this change for my PTZ camera card it look pretty nice.  Btw how do we use the tv-card-editor there no info on here.

**Comment by marrobHD** [comment]
> perfect its working much thank.  I using this change for my PTZ camera card it look pretty nice.  Btw how do we use the tv-card-editor there no info on here.

It's not in use any more. Implementing an easy edit mode was planned but I never finished because I stopped working on this project.

**Comment by maddeuce** [comment]
ok thank have a great weekend.

**Comment by mpkoslovsky** [comment]
Hello, I changed names and icons. But the image cannot refreshed, withou success. Could you help me please?
I changed reverse, play and forward to this code on tv-card.js

${
            this._config.hdmi1 || this._config.hdmi2 || this._config.hdmi3
              ? html`
                  <div class="row">
                    ${this._config.hdmi1
                      ? html`
                          <ha-icon-button
                            .action="${"hdmi1"}"
                            @click="${this.handleActionClick}"
                            icon="mdi:desktop-classsic"
                            title="Rewind"
                          ></ha-icon-button>
                        `
                      : emptyButton}
                    ${this._config.hdmi2
                      ? html`
                          <ha-icon-button
                            .action="${"hdmi2"}"
                            @click="${this.handleActionClick}"
                            icon="mdi:desktop-classsic"
                            title="hdmi2/Pause"
                          ></ha-icon-button>
                        `
                      : emptyButton}
                    ${this._config.hdmi3
                      ? html`
                          <ha-icon-button
                            .action="${"hdmi3"}"
                            @click="${this.handleActionClick}"
                            icon="mdi:desktop-classsic"
                            title="Fast-hdmi3"
                          ></ha-icon-button>
                        `
                      : emptyButton}
                  </div>
                `
              : ""
