### ISSUE TITLE
Purpose of tv-card-editor.js

### ISSUE THREAD

**Issue by pawlizio** [marrobHD/tv-card#4]
Is there a possibility to modify the remote layout? What is the purpose of tv-card-editor.js and how to use them in home-assistant.

**Comment by chrislawson** [comment]
this may be the file used when card is in edit mode in HA

**Comment by marrobHD** [comment]
Yes. The file tv-card-editor.js was used for a gui editor in HA. Unfortunately I stopped working on it.
