### ISSUE TITLE
"custom element doesn't exist" in some devices

### ISSUE THREAD

**Issue by piepolitb** [marrobHD/tv-card#5]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
last

**Last working release (if known):**

**Browser and Operating System:**
chrome

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by marrobHD** [comment]
Please provide more information

**Comment by szkari** [comment]
Yes, I cant update HA from 109 to new version because my remotes shows errors "custom element doesn't exist" on my adroid app. On Edge browser on PC everything is ok. 
I have newest version from HACS

**Comment by marrobHD** [comment]
Remove config of non existing integration from configuration.yaml. can you show me a screenshot of the issue that it won't update?

**Comment by ortodox** [comment]
Hey i love your card, but after update to version Home Assistant 0.111.4, i get error Custom element doesn't exist: tv-card.
![image](https://user-images.githubusercontent.com/30553299/85831320-67076b80-b78e-11ea-9404-fee25fda27ac.png)



the card was installed via HACS so i assume everything was taken cared of when it comes to installation.
![image](https://user-images.githubusercontent.com/30553299/85844032-637ddf80-b7a2-11ea-9875-367f3c1b6290.png)

**Comment by ortodox** [comment]
i have solved this issue, by updating HACS!
