### ISSUE TITLE
Only render buttons with configured actions

### ISSUE THREAD

**Issue by andersteern** [marrobHD/tv-card#7]
The current version of this card always renders almost all buttons even if I do not need them.

I would like to use this card as an Apple TV remote, and therefore need to make buttons optional

I made a suggestion in a [PR](https://github.com/marrobHD/tv-card/pull/6) on how to solve this.

Feedback is welcome

**Comment by djlca** [comment]
Yes; this would be a really helpful feature!

**Comment by marrobHD** [comment]
Thanks! Great work	andersteern. I merged it and [pushed](https://github.com/marrobHD/tv-card/releases/tag/0.1.2) it.
