### ISSUE TITLE
TV Card Stops Working After 0.110.0

### ISSUE THREAD

**Issue by luisiam** [marrobHD/tv-card#8]
**Checklist:**

- [x] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:** HA 0.110.0, TV Card 0.1.2

**Last working release (if known):** HA 0.109.6, TV Card 0.1.2

**Browser and Operating System:** Windows 10 with Chrome

**Description of problem:** After upgrading to HA 0.110.0, the card becomes blank without any buttons.

**Javascript errors shown in the web inspector (if applicable):**

```
None
```

**Additional information:**

**Comment by luisiam** [comment]
Sorry, that's a false alarm. Somehow it resumes working.

**Comment by wojtek14a** [comment]
I don't agree, I also have this issue after upgrading to 0.110.0, as well as with similar firetv-card. None of these issue is gone, it still requires attention

**Comment by luisiam** [comment]
Actually I still have this issue with another PC as well as on the phone. Tried everything and it is still there. I will just reopen the issue

**Comment by lilbuh** [comment]
same here no buttons showing 

> The way icons are handled was changed in 110 (quote from silvrr )

[homeassistant.io forums](https://community.home-assistant.io/t/force-reload-lovelace-missing-icons/197959)

**Comment by JozimarHM** [comment]
I really have a problem here, the buttons work, but the icons don't appear

![image](https://user-images.githubusercontent.com/58261216/82718079-a0702700-9c76-11ea-85df-166cada90214.png)

**Comment by mozan** [comment]
Same here. On PC, on phones.

Replacing `paper-icon-button` with `ha-icon-button` in `tv-card.js` does the trick. Just remove the `tv-card.js.gz` file.

I submitted a simple PR to fix the problem.

**Comment by marrobHD** [comment]
Merged it

**Comment by JozimarHM** [comment]
> O mesmo aqui. No PC, em telefones.
> 
> Substituir `paper-icon-button`por `ha-icon-button`em `tv-card.js`faz o truque. Apenas remova o `tv-card.js.gz`arquivo.
> 
> Enviei um PR simples para corrigir o problema.

Thank you! It solved my problem.

**Comment by JozimarHM** [comment]
> Same here. On PC, on phones.
> 
> Replacing `paper-icon-button` with `ha-icon-button` in `tv-card.js` does the trick. Just remove the `tv-card.js.gz` file.
> 
> I submitted a simple PR to fix the problem.

Thank you! It solved my problem.

**Comment by JozimarHM** [comment]
> Merged it

Thank you! It solved my problem.
