### ISSUE TITLE
Separating power buttons

### ISSUE THREAD

**Issue by wojtek14a** [marrobHD/tv-card#9]
**Is your feature request related to a problem? Please describe.**
My projector is controlled over RS232 and it takes different command (in HA different service) to power on and to power off.

**Describe the solution you'd like**
I'd like to be able to define different service to call for right and left power button.

**Describe alternatives you've considered**
Could use some other button but it looks not right to have 2 buttons to power on and still be forced to use some other to power it off.

**Additional context**
It would be worth considering using different icons, eg. `mdi:power-on` for the left one and `mdi:power` for the right one (same as now).

**Comment by Glivmo** [comment]
You could do this yourself by editing the tv-card.js file under "this._config.power".
You should edit the action, icon and title values.

Also add the value for action as another custom service in the list at the end of the file.

**Comment by marrobHD** [comment]
As @Glivmo said, you can do this manually. I haunt planed to include that. But I will include it if someone creates a pull request with a those features included.
